#!/usr/bin/perl

open LSCPU, "lscpu |" or print `uname`;
while (<LSCPU>)
{
    /(.+?):\s+(.+)/;
    $x{$1} = $2;
    $found = 1;
}

if ($found) {
    print "$x{'Vendor ID'}-$x{'CPU family'}.$x{Model}.$x{Stepping}_$x{'L1d cache'}\n"
}
